### ISSUE TITLE
"Pâclișa" is not found in database

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#10]
ENVIRONMENT:
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

STEPS TO REPRODUCE:

1.open SOLR in browser Chrome
2.in q section type "Pâclișa"
3.click on Execute Query button

EXPECTED RESULTS:
In the requirements document with diacritics there is "Pâclișa" component locality of Alba Iulia municipality in Alba county

ACTUAL RESULTS:
0 results; there is no "Pâclișa" component locality of Alba Iulia municipality in database

![image](https://user-images.githubusercontent.com/94704680/143104112-85a83db1-0d1c-4c63-bfb2-9a302979a69c.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 201753](https://github.com/peviitor-ro/orase/assets/118655267/2d2628dd-2c95-4a60-8b63-4550a3736d88)
Este municipiul Alba Iulia cu satul Paclisa.
