### ISSUE TITLE
"Gârbovița" is not found in database

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#11]
ENVIRONMENT:
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

STEPS TO REPRODUCE:

1.open SOLR in browser Chrome
2.in q section type "Gârbovița"
3.click on Execute Query button

EXPECTED RESULTS:
In the requirements document with diacritics there is "Gârbovița" component village of Aiud municipality in Alba county

ACTUAL RESULTS:
0 results; there is no "Gârbovița" component village of Aiud municipality in database
![image](https://user-images.githubusercontent.com/94704680/143115307-526b74fe-7062-4c8b-9d96-363be3dff717.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 201920](https://github.com/peviitor-ro/orase/assets/118655267/80a93be7-91ee-4e09-b5ef-b36c80382b78)
Este municipiul Aiud cu satul Garbovita.
