### ISSUE TITLE
"Țifra" is not found in database

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#12]
ENVIRONMENT:
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

STEPS TO REPRODUCE:

1.open SOLR in browser Chrome
2.in q section type "Țifra"
3.click on Execute Query button

EXPECTED RESULTS:
In the requirements document with diacritics there is "Țifra" component village of Aiud municipality in Alba county

ACTUAL RESULTS:
0 results; there is no "Țifra" component village of Aiud municipality in database
![image](https://user-images.githubusercontent.com/94704680/143121257-28d9c0d1-5fe3-4cdb-b8ec-7f97066c447f.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 202047](https://github.com/peviitor-ro/orase/assets/118655267/b16fcb85-4ef6-4e16-9ffc-ab4f2b8bc1b7)
Este municipiul Aiud cu satul Tifra.
