### ISSUE TITLE
"Micești" village is not found in database 

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#13]
**ENVIRONMENT:**
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

**STEPS TO REPRODUCE:**

1.open SOLR in browser
2.in q section type "Micești"
3.click on Execute Query button

**EXPECTED RESULTS:**
In the requirements document with diacritics there is :
"Micești" village of "Micești" township; 
"Casele Micești" village of "Feleacu" township; 
"Micești" village of "Țaga" township

**ACTUAL RESULTS**:
0 results; there is no "Micești" village of "Micești", "Feleacu" and "Țaga" townships in database, only in Alba Iulia
![image](https://user-images.githubusercontent.com/94175609/143125778-f349c522-22c3-4d16-8f43-45fe468ac632.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 202206](https://github.com/peviitor-ro/orase/assets/118655267/2a30c095-7149-44e7-aca0-e60057747386)
Este municipiul Alba Iulia cu satul Micesti.
