### ISSUE TITLE
"Ghimicești" village is not found in database

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#14]
**ENVIRONMENT:**
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Ghimice%C8%99ti&q.op=OR&indent=true&rows=182
browser: Chrome

**STEPS TO REPRODUCE:**

1.open SOLR in browser
2.in q section type "Ghimicești"
3.click on Execute Query button

**EXPECTED RESULTS:**
In the requirements document with diacritics there is "Ghimicești" village in "Fitionești" township

**ACTUAL RESULTS:**
0 results; there is no "Ghimicești" village of "Fitionești" township in database
![image](https://user-images.githubusercontent.com/94175609/143129918-ef897316-6e02-48f9-96b9-5b0e65cfb9cd.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 202933](https://github.com/peviitor-ro/orase/assets/118655267/7a4c8e5d-40a7-4f3a-92d1-e5ea91ba6a2b)
Este comuna Fitionesti cu satul Ghimicesti.
