### ISSUE TITLE
"Flitești" is not found in database

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#15]
ENVIRONMENT:
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

STEPS TO REPRODUCE:

1.open SOLR in browser Chrome
2.in q section type "Flitești"
3.click on Execute Query button

EXPECTED RESULTS:
In the requirements document with diacritics there is "Flitești" component locality of Blaj municipality in Alba county

ACTUAL RESULTS:
0 results; there is no "Flitești" component locality of Blaj municipality in database
![image](https://user-images.githubusercontent.com/94704680/143130060-7edd382a-cf2f-400d-9b42-90e7851e2f33.png)

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203144](https://github.com/peviitor-ro/orase/assets/118655267/3fb4180d-e948-4c38-9871-ad3e397b8b24)
Este municipiul Blaj cu satul Flitesti.
