### ISSUE TITLE
"Izvoarele" is not found in database as a component locality of Blaj municipality

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#16]
ENVIRONMENT:
SOLR: http://zimbor.go.ro/solr/#/romania/query?q=Mice%C8%99ti&q.op=OR&indent=true&rows=100
browser: Chrome

STEPS TO REPRODUCE:

1.open SOLR in browser Chrome
2.in q section type "Izvoarele"
3.click on Execute Query button

EXPECTED RESULTS:
In the requirements document expected 2 results for Alba county. There is only 1 result - "Izvoarele" component village of Livezile commune and "Izvoarele" didn't appear as a component locality of Blaj municipality. The both "Izvoarele" village/locality, are in Alba county

ACTUAL RESULTS: 
1 results; there is only "Izvoarele" component village of Livezile commune of Alba county in database
![image](https://user-images.githubusercontent.com/94704680/143134391-4d780bf2-e782-4f3a-89e6-463127557f65.png)
![image](https://user-images.githubusercontent.com/94704680/143135668-fa69496e-3e56-4ff4-b5e4-3ea55d932b40.png)

**Comment by ElizaRosoga** [comment]
https://orase.testquality.com defect [D4](https://orase.testquality.com/project/13054/result/2597568/defect/9509).

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D9](https://orase.testquality.com/project/13054/result/2596379/defect/9524).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D20](https://orase.testquality.com/project/13054/result/2604791/defect/9604).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203304](https://github.com/peviitor-ro/orase/assets/118655267/69af269b-5664-49fa-a539-15d397cf4468)
Este municipiul Blaj cu satul Izvoarele.
