### ISSUE TITLE
"Garbova de Sus" is not found

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#17]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query

Browser: Chrome

Steps to reproduce
1. Open SOLR in browser
2. Type Garbova de Sus in q field
3. 3. Click on execute query

Expected results: 
In the documents "Garbova de Sus" is displayed in Alba county

Actual results: 
"Garbova de Sus" is not displayed in Alba county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D1](https://orase.testquality.com/project/13054/result/2592114/defect/9487).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D2](https://orase.testquality.com/project/13054/result/2596376/defect/9488).

**Comment by ElizaRosoga** [comment]
https://orase.testquality.com defect [D3](https://orase.testquality.com/project/13054/result/2597565/defect/9508).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D19](https://orase.testquality.com/project/13054/result/2604788/defect/9603).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203422](https://github.com/peviitor-ro/orase/assets/118655267/e3918ab9-8827-4e12-a0ce-472883008a11)
Este municipiul Aiud cu satul Garbova de Sus.
