### ISSUE TITLE
Izvoarele is not found in Blaj municipality of Alba county

### ISSUE THREAD

**Issue by ElizaRosoga** [peviitor-ro/orase#18]
#### Precondition
URL:http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Open URL in Browser| SOLR UI is opened without any error| Pass |
| 2| Type Blaj in q field| You are able to type Blaj in q field| Pass |
| 3| Type judet:Alba in fq field| You are able to type judet:Alba in fq field| Pass |
| 4| Click on Execute Query button| The following 9 results are displayed:<br /><br>Blaj    <br /><br>Mănărade<br /><br>Deleni-Obârșie    <br /><br>Spătac<br /><br>Flitești    <br /><br>Izvoarele    <br /><br>Petrisat    <br /><br>Tiur    <br /><br>Veza| Fail |

Actual result:Izvoarele is not found in Blaj municipality of Alba county

**Comment by ElizaRosoga** [comment]
https://orase.testquality.com defect [D5](https://orase.testquality.com/project/13054/result/2597568/defect/9510).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203304](https://github.com/peviitor-ro/orase/assets/118655267/321ebca7-eb8f-43b3-8ad7-44dd5689bb58)
Municipiul Blaj cu satul Izvoarele.
