### ISSUE TITLE
[ALBA] List of components of Campeni, Alba county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#19]
#### Precondition
URL:http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Open URL in Browser| SOLR UI is opened without any error| Pass |
| 2| Type Campeni in q field| You are able to type Campeni in q field| Pass |
| 3| Type judet:Alba in fq field| You are able to type judet:Alba in fq field| Pass |
| 4| Type 100 in field: ROWS (next to START field)| You are able to type 100 in field: ROWS (next to START field)| Pass |
| 5| Click on Execute Query button| The following results are displayed: </p><br><ol><br><li>Campeni    </li><br><li>Boncești    </li><br><li>Borlești    </li><br><li><em>Botești</em>    </li><br><li>Certege    </li><br><li>Coasta Vâscului    </li><br><li>Dănduț    </li><br><li>Dealu Bistrii    </li><br><li>Dealu Capsei    </li><br><li>Dric    </li><br><li>Fața Abrudului    </li><br><li><em>Florești</em>    </li><br><li>*Furduiești    *</li><br><li>Mihoești    </li><br><li>Motorăști    </li><br><li>Peste Valea Bistrii    </li><br><li>Poduri    </li><br><li>Sorlița    </li><br><li>Tomușești    </li><br><li>Valea Bistrii    </li><br><li>Valea Caselor    </li><br><li>Vârși</li><br></ol>| Fail |
#### Actual Results: 
Botesti, Floresti and  Furduiesti and Valea Bistrii  are not found in the list of components of Campeni, Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_29859.png)
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_29860.png)
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_29861.png)
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_29862.png)
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_29863.png)

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D6](https://orase.testquality.com/project/13054/result/2597575/defect/9513).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D8](https://orase.testquality.com/project/13054/result/2597575/defect/9519).

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D10](https://orase.testquality.com/project/13054/result/2596386/defect/9525).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D21](https://orase.testquality.com/project/13054/result/2604798/defect/9605).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203743](https://github.com/peviitor-ro/orase/assets/118655267/bbc28b8c-b722-4bdb-b6ba-fdc1c66705ff)
Este orasul Campeni.
