### ISSUE TITLE
Infratirea, from Calarasi county, is not on ui.orase 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/orase#193]
![Infratirea_not_found](https://github.com/peviitor-ro/ui.orase/assets/129604131/a82ebc44-9073-4105-8d8c-ec1448152c6d)

**Comment by DianaDascalu2** [comment]
Avem comuna Dor Marunt, cu satul Infratirea.
![Screenshot 2024-02-28 155528](https://github.com/peviitor-ro/orase/assets/118655267/5d011c80-83f3-4580-97ed-d32e7768c42e)

**Comment by DeedeeDL** [comment]
Retested. Pass
