### ISSUE TITLE
[ALBA] Budăiești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#20]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Budăiești in q field
Click on execute query
Expected results:
In the documents "Budăiești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Budăiești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30130.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D11](https://orase.testquality.com/project/13054/result/2596400/defect/9540).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203848](https://github.com/peviitor-ro/orase/assets/118655267/c5a29076-2f44-4a54-b084-26930c93f73e)
Este comuna Albac cu satul Budaiesti.
