### ISSUE TITLE
[ALBA] Cionești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#21]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Cionești in q field
Click on execute query
Expected results:
In the documents "Cionești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Cionești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30131.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D12](https://orase.testquality.com/project/13054/result/2596401/defect/9541).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D22](https://orase.testquality.com/project/13054/result/2604813/defect/9606).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 203944](https://github.com/peviitor-ro/orase/assets/118655267/6bca0193-0c88-4805-984d-5ab4a46670a3)
Este comuna Albac cu satul Cionesti.
