### ISSUE TITLE
[ALBA] Costești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#22]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Costești in q field
Click on execute query
Expected results:
In the documents "Costești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Costești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30132.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D13](https://orase.testquality.com/project/13054/result/2596403/defect/9542).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 204043](https://github.com/peviitor-ro/orase/assets/118655267/d1657575-1e20-4597-ab83-060bf622a624)
Este comuna Albac cu satul Costesti.
