### ISSUE TITLE
[ALBA] Fața is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#23]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Fața in q field
Click on execute query
Expected results:
In the documents "Fața" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Fața" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30134.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D14](https://orase.testquality.com/project/13054/result/2596410/defect/9543).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D24](https://orase.testquality.com/project/13054/result/2604822/defect/9608).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 204152](https://github.com/peviitor-ro/orase/assets/118655267/b41f86b7-9d1c-4980-9873-491b4785077c)
Este comuna Albac cu satul Fata.
