### ISSUE TITLE
[ALBA] Pleșești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#24]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Pleșești in q field
Click on execute query
Expected results:
In the documents "Pleșești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Pleșești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30135.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D15](https://orase.testquality.com/project/13054/result/2596412/defect/9544).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 201210](https://github.com/peviitor-ro/orase/assets/118655267/db0d84ce-e593-4b36-ad6f-f5299c0a371e)
Este comuna Albac cu satul Plesesti.
