### ISSUE TITLE
[ALBA] Roșești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#25]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Roșești in q field
Click on execute query
Expected results:
In the documents "Roșești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Roșești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30136.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D16](https://orase.testquality.com/project/13054/result/2596416/defect/9545).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D25](https://orase.testquality.com/project/13054/result/2604828/defect/9609).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 201108](https://github.com/peviitor-ro/orase/assets/118655267/f3329939-117c-43b2-8a52-313ce41afdd7)
Este comuna Albac cu satul Rosesti.
