### ISSUE TITLE
[ALBA] Rusești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#26]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Rusești in q field
Click on execute query
Expected results:
In the documents "Rusești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Rusești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30137.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D17](https://orase.testquality.com/project/13054/result/2596418/defect/9546).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D26](https://orase.testquality.com/project/13054/result/2604830/defect/9610).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 201014](https://github.com/peviitor-ro/orase/assets/118655267/305f697e-8db0-49e6-98e4-4b4f49aae00f)
Este comuna Albac cu satul Rusesti.
