### ISSUE TITLE
[ALBA] Tamborești is a village in Albac commune from Alba county - Fail

### ISSUE THREAD

**Issue by danpaun2021** [peviitor-ro/orase#27]
Environment : Production
SOLR http://zimbor.go.ro/solr/#/romania/query
Browser: Chrome

Steps to reproduce

Open SOLR in browser
Type Tamborești in q field
Click on execute query
Expected results:
In the documents "Tamborești" village written with diacritics is found in Albac commune from Alba county

Actual results:
"Tamborești" village written with diacritics is not  found in database in Albac commune from Alba county
![](https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_RunResult_30138.png)

**Comment by danpaun2021** [comment]
https://orase.testquality.com defect [D18](https://orase.testquality.com/project/13054/result/2596421/defect/9547).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D27](https://orase.testquality.com/project/13054/result/2604833/defect/9611).
