### ISSUE TITLE
[ALBA] Almașu Mare village is not found in Almasu Mare commune from Alba county - Pending

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#28]
#### Precondition
URL: http://zimbor.go.ro/solr/#/romania/query?q.op=OR&indent=true
Browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| Open URL in Browser| SOLR is open in Browser without any errors| Pending |
| 2| Type Almașu Mare in q field| You are able to type Almașu Mare in q field| Pending |
| 3| Click on Execute Query| Almașu Mare village is found in Almasu Mare commune from Alba county| Pending |
#### Actual Results: 
Almașu Mare village is not found in Almasu Mare commune from Alba county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D28](https://orase.testquality.com/project/13054/result/2604835/defect/9612).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 195936](https://github.com/peviitor-ro/orase/assets/118655267/7ac03b3b-dccb-48df-9ca5-0d93d7a0add1)
Este comuna Almasu Mare cu satul Almasu Mare.
