### ISSUE TITLE
Strambeni village from Caldararu is not found in Arges county

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#37]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pass |
| 2| type one by one in the q field all the list of the components of every village in Arges county found in test data| you are able to type one by one in the q field  all the list of the components of every village in Arges county found in test data| Pass |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pass |
| 4| click on Execute Query button| Verify that all the list of the components of every village in judet:Arges form the test data are displayed</p><br><p><a href="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_30606.xlsx">Test data.xlsx</a>| Fail |
#### Actual Results: 
Strambeni village from Caldararu is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D37](https://orase.testquality.com/project/13054/result/2622367/defect/9655).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 194847](https://github.com/peviitor-ro/orase/assets/118655267/12a6042f-641c-468d-823c-80380481282d)
Este comuna Caldararu cu satul Strambeni.
