### ISSUE TITLE
The village Costesti doesn't appear for Albac from Alba county

### ISSUE THREAD

**Issue by andreealorena15** [peviitor-ro/orase#4]
Description: The village Costesti doesn't appear for Albac from Alba county after I'll search in the Solr database.
Test Steps:

1. I open the link in any browser;
  2. In section "Search Query" I insert the value "Costesti";
3. I press the button "Execute Query";
4. Notice that the village Costesti doesn't appear for Albac from Alba county. (in this database we have Costesti which make part another county e.g: Arges, Iasi, Valcea)
5. See the attached screenshot of the error page.

Expected Results: The village Costesti should be appeared for Albac from Alba county.
![Screenshot 2021-11-09 163536](https://user-images.githubusercontent.com/93220631/140943715-b397afc4-6978-4a42-b5b8-f9f30057dcfc.png)

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D7](https://orase.testquality.com/project/13054/result/2597592/defect/9518).

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D23](https://orase.testquality.com/project/13054/result/2604815/defect/9607).
