### ISSUE TITLE
[Arges] Brosteni village is a component of Costesti city, Arges county - Pending

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#43]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pending |
| 2| type Brosteni in the q field| you are able to type Brosteni in the q field| Pending |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pending |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Brosteni", "comuna: Costesti" are displayed| Pending |
#### Actual Results: 
Brosteni village is not found in Costesti city, Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D43](https://orase.testquality.com/project/13054/result/2622294/defect/9721).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 194114](https://github.com/peviitor-ro/orase/assets/118655267/d12593a1-225d-495b-adb4-e9c0922997cd)
Este orasul Costesti cu satul Brosteni.
