### ISSUE TITLE
[Arges] Golesti village is not found as a component of Stefanesti city, Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#44]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Golesti in the q field| You are able to type Golesti in the q field| Fail |
| 3| type judet: Arges in the fq field| you are able to type judet: Arges in the fq field| Fail |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Golesti", "comuna: Stefanesti" are displayed| Fail |
#### Actual Results: 
Golesti village is not found as a component of Stefanesti city, Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D44](https://orase.testquality.com/project/13054/result/2622305/defect/9722).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 194000](https://github.com/peviitor-ro/orase/assets/118655267/6622b5f5-02fb-4baf-8ae5-f4e95285af58)
Este orasul Stefanesti cu satul Golesti.
