### ISSUE TITLE
[Arges] Valea Mare-Podgoria village is not a component of Stefanesti city, Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#45]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Valea Mare-Podgoria in the q field| you are able to type Valea Mare-Podgoria in the q field| Fail |
| 3| type judet: Arges in the fq field| you are able to type judet: Arges in the fq field| Fail |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Valea Mare-Podgoria", "comuna: Stefanesti" are displayed| Fail |
#### Actual Results: 
Valea Mare-Podgoria village is not found as a component of Stefanesti city, Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D45](https://orase.testquality.com/project/13054/result/2622308/defect/9723).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193851](https://github.com/peviitor-ro/orase/assets/118655267/bf804533-1079-4d9a-be21-102db7e95658)
Este orasul Stefanesti cu satul Valea Mare-Podgoria.
