### ISSUE TITLE
[Arges] Stefanesti is not found in Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#46]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Stefanesti in the q field| type Stefanesti in the q field| Fail |
| 3| click on Execute Query button| "judet:Arges" and "localitate : Stefanesti" are displayed| Fail |
#### Actual Results: 
Stefanesti city is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D46](https://orase.testquality.com/project/13054/result/2622317/defect/9724).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193744](https://github.com/peviitor-ro/orase/assets/118655267/903a0ff1-c91a-4efa-8eb1-105979d5e6c3)
Este orasul Stefanesti.
