### ISSUE TITLE
[Arges] Albestii Ungureni is not found in Albestii de Arges village in Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#47]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Albestii Ungureni in the q field| youare able to type Albestii Ungureni in the q field| Fail |
| 3| type judet: Arges in the fq fied| you are able to type judet:Arges in the fq field| Fail |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Albestii Ungureni ", "comuna: Albestii de Arges" are displayed| Fail |
#### Actual Results: 
Albestii Ungureni is not found in Albestii de Arges village in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D47](https://orase.testquality.com/project/13054/result/2622321/defect/9725).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193617](https://github.com/peviitor-ro/orase/assets/118655267/b037fb52-058f-468f-93c6-c384a9f3b1d2)
Este comuna Albestii de Arges cu satul Albestii Ungureni.
