### ISSUE TITLE
[Arges] Mica component of Bascov village is not found in Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#48]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Mica in the q field| you are able to type Mica in the q field| Fail |
| 3| type judet: Arges in the fq field| you are able to type judet: Arges in the fq field| Fail |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Mica", "comuna: Bascov " are displayed| Fail |
#### Actual Results: 
Mica component of Bascov village is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D48](https://orase.testquality.com/project/13054/result/2622345/defect/9726).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193505](https://github.com/peviitor-ro/orase/assets/118655267/156de5bc-bc7c-48c2-8562-2e87d8ddbefc)
Este comuna Bascov cu satul Mica.
