### ISSUE TITLE
[Arges] Schiau component of Bascov village is not found in Arges county - Pending

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#49]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pending |
| 2| type Schiau in the q field| you are able to type Schiau in the q field| Pending |
| 3| type judet: Arges in the fq field| you are able to type judet: Arges in the fq field| Pending |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Schiau", "comuna:Bascov" are displayed| Pending |
#### Actual Results: 
Schiau component of Bascov village is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D49](https://orase.testquality.com/project/13054/result/2622347/defect/9727).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193341](https://github.com/peviitor-ro/orase/assets/118655267/1ba08c73-8952-449d-a1be-a7015c83d10c)
Este comuna Bascov cu satul Schiau.
