### ISSUE TITLE
[Arges] Slatioarele component of Babana village  is not found in Arges county - Fail

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#50]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Fail |
| 2| type Slatioarele in the q field| you are able to type Slatioarele in the q field| Fail |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Fail |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Slatioarele", "comuna: Babana" are displayed| Fail |
#### Actual Results: 
Slatioarele component of Babana village is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D50](https://orase.testquality.com/project/13054/result/2622356/defect/9728).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193144](https://github.com/peviitor-ro/orase/assets/118655267/d5a59158-8aeb-4f65-bfc7-c35317e7d352)
Este comuna Babana cu satul Slatioarele.
