### ISSUE TITLE
[Arges] Alunisu component of Baiculesti village is not found in Arges county - Pending

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#51]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pending |
| 2| type Alunisu in the q field| you are able to type Alunisu in the q field| Pending |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pending |
| 4| click on Execute Query button| "judet:Arges" and "localitate: Alunisu", "comuna: Baiculesti" are displayed| Pending |
#### Actual Results: 
Alunisu component of Baiculesti village is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D51](https://orase.testquality.com/project/13054/result/2622358/defect/9729).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 193014](https://github.com/peviitor-ro/orase/assets/118655267/1ac77e92-35c9-407a-9848-cd71bde74cb5)
Este comuna Baiculesti cu satul Alunisu.
