### ISSUE TITLE
Ciofrangeni village is not found in Arges county

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#53]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pass |
| 2| type one by one in the q field all the list of the components of every village in Arges county found in test data| you are able to type one by one in the q field  all the list of the components of every village in Arges county found in test data| Pass |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pass |
| 4| click on Execute Query button| Verify that all the list of the components of every village in judet:Arges form the test data are displayed| Fail |
#### Actual Results: 
Ciofringeni village is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D52](https://orase.testquality.com/project/13054/result/2622367/defect/9732).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 192848](https://github.com/peviitor-ro/orase/assets/118655267/8bde26df-15b1-4b70-ac5d-ed758a963577)
Este comuna Ciofrangeni cu satul Ciofrangeni.
