### ISSUE TITLE
Corbi village component of Corbi is not found in Arges county

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#60]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pass |
| 2| type one by one in the q field all the list of the components of every village in Arges county found in test data| you are able to type one by one in the q field  all the list of the components of every village in Arges county found in test data| Pass |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pass |
| 4| click on Execute Query button| Verify that all the list of the components of every village in judet:Arges form the test data are displayed| Fail |
#### Actual Results: 
Corbi village component of Corbi is not found in Arges county

**Comment by Kristinica** [comment]
https://orase.testquality.com defect [D59](https://orase.testquality.com/project/13054/result/2622367/defect/9739).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 192104](https://github.com/peviitor-ro/orase/assets/118655267/4e2f1b49-3d6a-4c62-a17f-859adc329ca1)
Este comuna Corbi cu satul Corbi.
