### ISSUE TITLE
Dambovicioara village component of Dambovicioara is not found in Arges county

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#68]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pass |
| 2| type one by one in the q field all the list of the components of every village in Arges county found in test data| you are able to type one by one in the q field  all the list of the components of every village in Arges county found in test data| Pass |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pass |
| 4| click on Execute Query button| Verify that all the list of the components of every village in judet:Arges form the test data are displayed| Fail |
#### Actual Results: 
Dambovicioara village component of Dambovicioara is not found in Arges county

**Comment by Kristinica** [comment]
Open defect in TestQuality [D68](https://web.testquality.com/site/orase/project/13054?defectId=9799)
- Test [List of the components of every village in Arges county](https://web.testquality.com/site/orase/project/13054/runs/154119?resultId=2622367) in Run [Run 6](https://web.testquality.com/site/orase/project/13054/runs/154119) (linked to Cycle [Sprint 1](https://web.testquality.com/site/orase/project/13054/cycles/22990)).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 191015](https://github.com/peviitor-ro/orase/assets/118655267/e1de6abc-92a0-423b-90fa-9712af93d8ce)
Este comuna Dambovicioara cu satul Dambovicioara.
