### ISSUE TITLE
Dobresti village component of Dobresti is not found in Arges county

### ISSUE THREAD

**Issue by Kristinica** [peviitor-ro/orase#70]
#### Precondition
SOLR: http://zimbor.go.ro/solr/#/romania/query
browser: Chrome
#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| open SOLR in browser| SOLR UI is loaded without any errors| Pass |
| 2| type one by one in the q field all the list of the components of every village in Arges county found in test data| you are able to type one by one in the q field  all the list of the components of every village in Arges county found in test data| Pass |
| 3| type judet: Arges in the fq field| you are able to type judet:Arges in the fq field| Pass |
| 4| click on Execute Query button| Verify that all the list of the components of every village in judet:Arges form the test data are displayed| Fail |
#### Actual Results: 
 Dobresti village component of Dobresti is not found in Arges county

**Comment by Kristinica** [comment]
Open defect in TestQuality [D70](https://web.testquality.com/site/orase/project/13054?defectId=9801)
- Test [List of the components of every village in Arges county](https://web.testquality.com/site/orase/project/13054/runs/154119?resultId=2622367) in Run [Run 6](https://web.testquality.com/site/orase/project/13054/runs/154119) (linked to Cycle [Sprint 1](https://web.testquality.com/site/orase/project/13054/cycles/22990)).

**Comment by DianaDascalu2** [comment]
![Screenshot 2024-01-26 190720](https://github.com/peviitor-ro/orase/assets/118655267/8e294166-fc4b-4398-a356-7f1df80c5c8c)
Este comuna Dobresti cu satul Dobresti.
